apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: deployement
  labels:
    app: MYAPP-deploye
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      containers:
      - name: nginx
        image: nginx/nginx
        