apiVersion: v1
kind: Pod
metadata:
  name: tolerations
  labels:
    name: webapp
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "app"
    operator: "equal"
    value: "database"
    effect: "NoSchedule"