apiVersion: v1
kind: Pod
metadata:
  name: limitpod
spec:
  containers:
  - name: app
    image: nginx:latest
    resource:
      requests:
        memory: "40Mi"
        cpu: "80m"
      limits:
        memory: "80Mi"
        cpu: "200m"
