apiVersion: v1
kind: Pod
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
  - name: apple-app
    image: hashicrop/http-echo
    args:
      - "-text=apple"

---

apiVersion: v1
kind: Service
metadata:
  name: apple-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: apple-app
  ports:
    - port: 5678

  