apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: 40Mi
            cpu: 1m
          requests:
            cpu: 1m
            memory: 30Mi
        